name: Makefile CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make install

    - name: Lint with pylint
      run: make lint

    - name: Test with pytest
      run: make test

    - name: Format code
      run: make format
